// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/filter-panel-usability/Accessible.tsx": () => import("../components/mockups/filter-panel-usability/Accessible.tsx"),
  "./components/mockups/filter-panel-usability/Hierarchy.tsx": () => import("../components/mockups/filter-panel-usability/Hierarchy.tsx"),
  "./components/mockups/filter-panel-usability/Interaction.tsx": () => import("../components/mockups/filter-panel-usability/Interaction.tsx")
};
