import io
import textwrap
from PIL import Image, ImageDraw, ImageFont


def _draw_wrapped(draw: ImageDraw.ImageDraw, text: str, x: int, y: int, width_chars: int, font: ImageFont.ImageFont, line_height: int, fill: tuple[int, int, int]) -> int:
    lines = textwrap.wrap(text, width=width_chars) or [""]
    for line in lines:
        draw.text((x, y), line, font=font, fill=fill)
        y += line_height
    return y


def _section(draw: ImageDraw.ImageDraw, title: str, lines: list[str], x: int, y: int, width_chars: int, title_font: ImageFont.ImageFont, body_font: ImageFont.ImageFont) -> int:
    y = _draw_wrapped(draw, title, x, y, width_chars, title_font, 24, (20, 32, 60))
    y += 4
    for line in lines:
        y = _draw_wrapped(draw, line, x, y, width_chars, body_font, 20, (35, 35, 35))
    return y + 10


def _new_canvas() -> tuple[Image.Image, ImageDraw.ImageDraw, ImageFont.ImageFont, ImageFont.ImageFont, ImageFont.ImageFont]:
    img = Image.new("RGB", (1240, 1754), color=(255, 255, 255))
    draw = ImageDraw.Draw(img)
    title_font = ImageFont.load_default()
    body_font = ImageFont.load_default()
    small_font = ImageFont.load_default()
    return img, draw, title_font, body_font, small_font


def generate_health_summary_pdf(graph_data: dict) -> bytes:
    img, draw, title_font, body_font, small_font = _new_canvas()

    y = 70
    draw.text((80, y), "CareOrbit Health Summary", font=title_font, fill=(0, 34, 84))
    y += 40

    summary = graph_data.get("summary", {}) if graph_data else {}
    total_nodes = summary.get("total_nodes", 0)
    meds = graph_data.get("medications", []) if graph_data else []
    interactions = graph_data.get("interactions", []) if graph_data else []
    care_gaps = graph_data.get("care_gaps", []) if graph_data else []

    y = _section(
        draw,
        "Overview",
        [
            f"Total health nodes indexed: {total_nodes}",
            f"Active medications detected: {len(meds)}",
            f"Interaction alerts detected: {len(interactions)}",
            f"Open care gaps detected: {len(care_gaps)}",
        ],
        80,
        y,
        115,
        title_font,
        body_font,
    )

    if meds:
        lines = []
        for med in meds[:8]:
            med_name = med.get("name") or "Unknown medication"
            dose = med.get("dosage") or ""
            freq = med.get("frequency") or ""
            details = " ".join(part for part in [dose, freq] if part)
            lines.append(f"- {med_name} {details}".strip())
        y = _section(draw, "Medication Snapshot", lines, 80, y, 115, title_font, body_font)

    if interactions:
        lines = []
        for ix in interactions[:6]:
            pair = ix.get("drug_pair", "Unknown pair")
            severity = (ix.get("severity") or "unknown").upper()
            action = ix.get("clinical_action") or "Review with clinician"
            lines.append(f"- {pair} [{severity}] -> {action}")
        y = _section(draw, "Interaction Risks", lines, 80, y, 115, title_font, body_font)

    if care_gaps:
        lines = []
        for gap in care_gaps[:6]:
            lines.append(f"- {gap.get('name', 'Unknown care gap')} ({gap.get('status', 'open')})")
        y = _section(draw, "Care Gaps", lines, 80, y, 115, title_font, body_font)

    y = _section(
        draw,
        "Clinical Next Steps",
        [
            "- Continue medication adherence and maintain reminder logging.",
            "- Prioritize doctor review for abnormal trends and interaction burden.",
            "- Repeat key labs at next review interval and compare trajectory.",
        ],
        80,
        y,
        115,
        title_font,
        body_font,
    )

    draw.text((80, min(y + 12, 1670)), "Generated by CareOrbit Healthcare AI Platform", font=small_font, fill=(85, 85, 85))

    buffer = io.BytesIO()
    img.save(buffer, format="PDF", resolution=100.0)
    return buffer.getvalue()


def generate_previsit_doctor_brief_pdf(brief: dict) -> bytes:
    img, draw, title_font, body_font, small_font = _new_canvas()

    y = 70
    draw.text((80, y), "CareOrbit Pre-Visit Doctor Brief", font=title_font, fill=(0, 34, 84))
    y += 40

    patient = brief.get("patient", {})
    appt = brief.get("appointment", {})

    y = _section(
        draw,
        "Patient + Visit Context",
        [
            f"Patient: {patient.get('name', 'Patient')} | Age: {patient.get('age', 'N/A')} | Gender: {patient.get('gender', 'N/A')}",
            f"Doctor: {appt.get('doctor_name', 'Unknown')} ({appt.get('specialization', 'General')})",
            f"Visit Time: {appt.get('appointment_datetime', 'N/A')}",
            f"Clinic: {appt.get('clinic_name', 'N/A')}",
        ],
        80,
        y,
        115,
        title_font,
        body_font,
    )

    meds = brief.get("medications", [])
    if meds:
        med_lines = [f"- {m.get('name', 'Unknown')} {m.get('dosage', '')} ({m.get('frequency', '')})".strip() for m in meds[:8]]
        y = _section(draw, "Current Medications", med_lines, 80, y, 115, title_font, body_font)

    labs = brief.get("labs", [])
    if labs:
        lab_lines = []
        for lab in labs[:10]:
            state = "ABNORMAL" if lab.get("abnormal") else "NORMAL"
            rng = lab.get("reference_range") or "range unavailable"
            lab_lines.append(f"- {lab.get('name')}: {lab.get('value')} {lab.get('unit', '')} [{state}] (ref: {rng})")
        y = _section(draw, "Lab Highlights", lab_lines, 80, y, 115, title_font, body_font)

    priorities = brief.get("clinical_priorities", [])
    if priorities:
        y = _section(draw, "Clinical Priorities", [f"- {p}" for p in priorities], 80, y, 115, title_font, body_font)

    risks = brief.get("interaction_risks", [])
    if risks:
        risk_lines = [f"- {r.get('drug_pair', 'Unknown pair')} [{r.get('severity', 'unknown')}]" for r in risks[:6]]
        y = _section(draw, "Medication Interaction Risks", risk_lines, 80, y, 115, title_font, body_font)

    care_gaps = brief.get("care_gaps", [])
    if care_gaps:
        gap_lines = [f"- {g.get('name', 'Unknown')} ({g.get('status', 'open')})" for g in care_gaps[:6]]
        y = _section(draw, "Preventive Care Gaps", gap_lines, 80, y, 115, title_font, body_font)

    draw.text((80, min(y + 12, 1670)), "Generated by CareOrbit Healthcare AI Platform", font=small_font, fill=(85, 85, 85))

    buffer = io.BytesIO()
    img.save(buffer, format="PDF", resolution=100.0)
    return buffer.getvalue()
