def generate_health_summary_pdf(graph_data: dict) -> bytes:
    content = "%PDF-1.4 CareOrbit Health Summary\n"
    if graph_data and "summary" in graph_data:
        total = graph_data["summary"].get("total_nodes", 0)
        content += f"Total health nodes: {total}\n"
    content += "Generated by CareOrbit Healthcare AI Platform\n"
    return content.encode("utf-8")
