from fastapi import APIRouter, Request
from fastapi import HTTPException
from fastapi.responses import StreamingResponse
import io
from datetime import datetime

import api.middleware.auth as auth_mod
from api.middleware.rbac import verify_patient_access
from graph.phig_builder import phig_builder
from utils.pdf_generator import generate_health_summary_pdf
from services.azure_blob import AzureBlobService
from api.routes.orbit import _appointments_store
from db.seed_demo import RAMESH_LABS, RAMESH_MEDICATIONS, DEMO_USER_ID

blob_service = AzureBlobService()

router = APIRouter(prefix="/api/summary", tags=["summary"])


def _build_previsit_brief_pdf(appointment: dict, patient_id: str) -> bytes:
    lines = [
        "%PDF-1.4 CareOrbit Pre-Visit Brief",
        f"Patient: {patient_id}",
        f"Doctor: {appointment.get('doctor_name', 'Unknown')}",
        f"Specialization: {appointment.get('specialization', 'General')}",
        f"Appointment Time: {appointment.get('appointment_datetime', '')}",
        f"Clinic: {appointment.get('clinic_name', '')}",
        f"Generated At: {datetime.utcnow().isoformat()}Z",
        "",
        "Current medications:",
    ]
    for med in RAMESH_MEDICATIONS[:5]:
        lines.append(f"- {med['name']} {med.get('dosage', '')} ({med.get('frequency', '')})")

    lines.append("")
    lines.append("Recent labs and flags:")
    for lab in RAMESH_LABS:
        flag = "ABNORMAL" if lab.get("abnormal") else "NORMAL"
        lines.append(f"- {lab['name']}: {lab['value']} {lab.get('unit', '')} [{flag}]")

    lines.append("")
    lines.append("Clinical focus for this visit:")
    lines.append("- Review diabetes control trajectory and adherence issues.")
    lines.append("- Assess renal safety and interaction risk mitigation.")
    lines.append("Generated by CareOrbit Healthcare AI Platform")
    return "\n".join(lines).encode("utf-8")


@router.get("/generate")
async def generate_summary(request: Request):
    current_user = await auth_mod.get_current_user(request)
    patient_id = request.query_params.get("patient_id", current_user["id"])

    await verify_patient_access(current_user["id"], patient_id)

    graph_data = await phig_builder.get_full_patient_graph(patient_id)

    total_nodes = 0
    if graph_data and "summary" in graph_data:
        total_nodes = graph_data["summary"].get("total_nodes", 0)

    if total_nodes == 0:
        return {"error": "No health data available to generate summary"}

    pdf_bytes = generate_health_summary_pdf(graph_data)

    try:
        await blob_service.upload_health_summary_pdf(pdf_bytes, f"CareOrbit_Summary_{patient_id}.pdf")
    except (NotImplementedError, Exception):
        pass

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="CareOrbit_Summary_{patient_id}.pdf"'
        }
    )


@router.get("/previsit-brief/{appointment_id}")
async def generate_previsit_brief(appointment_id: str, request: Request):
    current_user = await auth_mod.get_current_user(request)
    patient_id = request.query_params.get("patient_id", current_user["id"])
    await verify_patient_access(current_user["id"], patient_id)

    appointments = _appointments_store.get(patient_id, [])
    appointment = next((a for a in appointments if a.get("appointment_id") == appointment_id), None)
    if appointment is None and patient_id == DEMO_USER_ID:
        appointment = next((a for a in _appointments_store.get(DEMO_USER_ID, []) if a.get("appointment_id") == appointment_id), None)

    if appointment is None:
        raise HTTPException(status_code=404, detail="Appointment not found")

    pdf_bytes = _build_previsit_brief_pdf(appointment, patient_id)
    filename = f"CareOrbit_PreVisit_{appointment_id}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
